Create google sheet_Wifi_Connectivity
Compiling sketch...
"C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/config" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid/api" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_trace" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_update" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bootloader_support" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bt" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/driver" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_adc_cal" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_http_client" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp-tls" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ethernet" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/fatfs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/freertos" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/heap" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/jsmn" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/log" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mdns" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls_port" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nvs_flash" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/openssl" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spi_flash" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/sdmmc" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/smartconfig_ack" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spiffs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/tcpip_adapter" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ulp" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/vfs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wear_levelling" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/xtensa-debug-module" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/coap" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/console" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/expat" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/json" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/lwip" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nghttp" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/soc" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="ESP32_DEV" -DARDUINO_VARIANT="esp32"  -DESP32 -DCORE_DEBUG_LEVEL=0  "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\cores\esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\variants\esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src" "-IC:\Program Files (x86)\Arduino\libraries\WiFi\src" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\SPI\src" "C:\Users\eachbar\AppData\Local\Temp\arduino_build_266156\sketch\sketch_sep19a.ino.cpp" -o "C:\Users\eachbar\AppData\Local\Temp\arduino_build_266156\sketch\sketch_sep19a.ino.cpp.o"
Compiling libraries...
Compiling library "WiFiClientSecure"
"C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/config" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bluedroid/api" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_trace" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/app_update" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bootloader_support" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/bt" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/driver" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_adc_cal" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp_http_client" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp-tls" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ethernet" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/fatfs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/freertos" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/heap" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/jsmn" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/log" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mdns" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/mbedtls_port" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nvs_flash" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/openssl" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spi_flash" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/sdmmc" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/smartconfig_ack" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/spiffs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/tcpip_adapter" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ulp" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/vfs" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wear_levelling" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/xtensa-debug-module" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/coap" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/console" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/expat" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/json" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/lwip" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/newlib" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/nghttp" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/soc" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -MMD -c -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="ESP32_DEV" -DARDUINO_VARIANT="esp32"  -DESP32 -DCORE_DEBUG_LEVEL=0  "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\cores\esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\variants\esp32" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src" "-IC:\Program Files (x86)\Arduino\libraries\WiFi\src" "-IC:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\SPI\src" "C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp" -o "C:\Users\eachbar\AppData\Local\Temp\arduino_build_266156\libraries\WiFiClientSecure\WiFiClientSecure.cpp.o"
C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In constructor 'WiFiClientSecure::WiFiClientSecure()':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:33:5: error: '_connected' was not declared in this scope

     _connected = false;

     ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In constructor 'WiFiClientSecure::WiFiClientSecure(int)':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:48:5: error: '_connected' was not declared in this scope

     _connected = false;

     ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'WiFiClientSecure& WiFiClientSecure::operator=(const WiFiClientSecure&)':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:74:5: error: '_connected' was not declared in this scope

     _connected = other._connected;

     ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:74:24: error: 'const class WiFiClientSecure' has no member named '_connected'

     _connected = other._connected;

                        ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'virtual void WiFiClientSecure::stop()':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:83:9: error: '_connected' was not declared in this scope

         _connected = false;

         ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'int WiFiClientSecure::connect(const char*, uint16_t, const char*, const char*, const char*)':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:113:5: error: '_connected' was not declared in this scope

     _connected = true;

     ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'virtual size_t WiFiClientSecure::write(const uint8_t*, size_t)':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:149:10: error: '_connected' was not declared in this scope

     if (!_connected) {

          ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'virtual int WiFiClientSecure::available()':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:190:10: error: '_connected' was not declared in this scope

     if (!_connected) {

          ^

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp: In member function 'virtual uint8_t WiFiClientSecure::connected()':

C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure\src\WiFiClientSecure.cpp:207:12: error: '_connected' was not declared in this scope

     return _connected;

            ^

Using library WiFiClientSecure at version 1.0 in folder: C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure 
Using library WiFi at version 1.2.7 in folder: C:\Program Files (x86)\Arduino\libraries\WiFi 
Using library SPI at version 1.0 in folder: C:\Users\eachbar\Documents\Arduino\hardware\espressif\esp32\libraries\SPI 
exit status 1
Error compiling for board ESP32 Dev Module.